const fs = require('fs');
const path = require('path');

// Locate repo root (assume script runs from repo root) and ports.json
const repoRoot = path.resolve(__dirname, '..');
const portsPath = path.join(repoRoot, 'ports.json');

if (!fs.existsSync(portsPath)) {
  console.error('ports.json not found at', portsPath);
  process.exit(1);
}

const ports = JSON.parse(fs.readFileSync(portsPath, 'utf8'));
const wsPort = ports.ws_port || 9100;

const demoDir = path.join(repoRoot, 'Documents', 'game101', 'Downloads', 'recovered_nucleus_eye', 'world-engine-feat-v3-1-advanced-math');
const outFile = path.join(demoDir, 'ConsciousnessFeedbackDemo_ports_config.ts');

const content = `// This file is generated by scripts/generate_ports_config.js
export const WS_URL = 'ws://localhost:${wsPort}';
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log('Wrote', outFile);
